In [2]:
import tensorflow as tf

/Users/bititudetechnologies/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [3]:
 print(tf.reduce_sum(tf.random.normal([1000, 1000])))

tf.Tensor(-8.323334, shape=(), dtype=float32)


In [4]:
print(tf.config.list_physical_devices('GPU'))

[]


In [5]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [6]:
y=tf.constant(5)
print(y)

tf.Tensor(5, shape=(), dtype=int32)


In [7]:
z=tf.contant()
print(z)

AttributeError: module 'tensorflow' has no attribute 'contant'

In [ ]:
tf.constant([[1,2,3],[4,5,6]],shape=(3,2))


In [ ]:
a=tf.constant([[1,2],
             [2,3],
             [3,4]],shape=(3,2))
a.shape


CHAGNE DATA TYPE

In [8]:
tf_float32=tf.constant(3.12345,tf.float32)
tf_int=tf.cast(tf_float32,dtype=tf.int32)
print(tf_float32.dtype)
print(tf_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


CREATING OPERATOR

In [9]:
x=tf.constant([2.0],tf.float32)
print(tf.sqrt(x))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)


In [10]:
x1=tf.constant([1,2,3])
x2=tf.constant([4,5,6])
z1=tf.add(x1,x2)
print(z1)
z2=x1+x2
print(z2)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [11]:
z3=tf.multiply(x1,x2)
print(z3)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [12]:
b=tf.constant([[1,2,3],
               [3,4,5]])
c=tf.constant([[1,2,3],
             [3,4,5],
             [5,6,7]])
d=tf.matmul(b,c)
print(d)

tf.Tensor(
[[22 28 34]
 [40 52 64]], shape=(2, 3), dtype=int32)


INDEXING

In [13]:
a1=tf.constant([1,2,3,4,5,6,7,8])
print(a1[:])
print(a1[1::])
print(a1[1:3])
print(a1[::2])
print(a1[::-1])


tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8], shape=(7,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1], shape=(8,), dtype=int32)


RESHAPING

In [15]:
x=tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


EAGER EXECUTION

In [16]:
import tensorflow as tf
a=tf.constant(1.2)
b=tf.constant(2.2)
c=a+b
print(c)

tf.Tensor(3.4, shape=(), dtype=float32)


In [17]:
@tf.function
def add(a,b):
    return a+b
a1=tf.constant(2.2)
a2=tf.constant(4.2)
output=a1+a2
print(output)

tf.Tensor(6.3999996, shape=(), dtype=float32)


VARIABLE

In [21]:
v=tf.Variable(1.1)
v.assign(2.2)
v.assign_add(.4)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.6000001430511475>


In [24]:
w=tf.constant(1)
w.assign(3)
print(w)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign_add'