In [1]:
import tensorflow as tf

/Users/bititudetechnologies/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [4]:
 print(tf.reduce_sum(tf.random.normal([1000, 1000])))

tf.Tensor(-39.506927, shape=(), dtype=float32)


In [5]:
print(tf.config.list_physical_devices('GPU'))

[]


In [7]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [9]:
y=tf.constant(5)
print(y)

tf.Tensor(5, shape=(), dtype=int32)


In [10]:
z=tf.contant()
print(z)

AttributeError: module 'tensorflow' has no attribute 'contant'

In [17]:
tf.constant([[1,2,3],[4,5,6]],shape=(3,2))


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [22]:
a=tf.constant([[1,2],
             [2,3],
             [3,4]],shape=(3,2))
a.shape


TensorShape([3, 2])

CHAGNE DATA TYPE

In [26]:
tf_float32=tf.constant(3.12345,tf.float32)
tf_int=tf.cast(tf_float32,dtype=tf.int32)
print(tf_float32.dtype)
print(tf_int.dtype)

<dtype: 'float32'>
<dtype: 'int32'>


CREATING OPERATOR

In [29]:
x=tf.constant([2.0],tf.float32)
print(tf.sqrt(x))

tf.Tensor([1.4142135], shape=(1,), dtype=float32)


In [31]:
x1=tf.constant([1,2,3])
x2=tf.constant([4,5,6])
z1=tf.add(x1,x2)
print(z1)
z2=x1+x2
print(z2)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [32]:
z3=tf.multiply(x1,x2)
print(z3)

tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)


In [37]:
b=tf.constant([[1,2,3],
               [3,4,5]])
c=tf.constant([[1,2,3],
             [3,4,5],
             [5,6,7]])
d=tf.matmul(b,c)
print(d)

tf.Tensor(
[[22 28 34]
 [40 52 64]], shape=(2, 3), dtype=int32)


INDEXING

In [44]:
a1=tf.constant([1,2,3,4,5,6,7,8])
print(a1[:])
print(a1[1::])
print(a1[1:3])
print(a1[::2])
print(a1[::-1])


tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)
tf.Tensor([2 3 4 5 6 7 8], shape=(7,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)
tf.Tensor([8 7 6 5 4 3 2 1], shape=(8,), dtype=int32)


RESHAPING

In [55]:
x=tf.range(9)
print(w)
print(v)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
