In [1]:
import numpy
numpy.__version__


'2.0.2'

In [2]:
import numpy as np

In [3]:
list=[1,2,3,4]

In [4]:
np.array(list)

array([1, 2, 3, 4])

In [7]:
np.array(list, dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [8]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [10]:
np.zeros((3,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [11]:
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.random.random((3,3))

array([[0.73123009, 0.39132891, 0.66646575],
       [0.27524986, 0.46333753, 0.83434276],
       [0.75289666, 0.51841212, 0.39393257]])

In [18]:
np.random.randint(0,10,(3,3))

array([[2, 7, 0],
       [1, 4, 0],
       [3, 9, 9]])

In [19]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.random.seed(1)

In [32]:
np.random.seed(1)
np.random.randint(10,size=6)

array([5, 8, 9, 5, 0, 0])

In [31]:
np.random.randint(10,size=(3,3))

array([[1, 7, 9],
       [8, 4, 0],
       [1, 9, 8]])

In [40]:
x=np.random.randint(10,size=(3,5,6))

In [35]:
print(x.ndim)

3


In [36]:
print(x.shape)

(3, 5, 6)


In [37]:
print(x.size)

90


In [38]:
print(x.dtype)

int64


In [39]:
print(x.itemsize)

8


In [41]:
print(x.nbytes)

720


In [42]:
np.random.seed(1)
x1=np.random.randint(10,size=6)

In [43]:
print(x1)
x1[0]

[5 8 9 5 0 0]


np.int64(5)

In [44]:
np.random.seed(1)

In [45]:
x2=np.random.randint(10,size=(3,3))

In [46]:
print(x2)

[[5 8 9]
 [5 0 0]
 [1 7 6]]


In [47]:
x2[0,1]

np.int64(8)